### ISSUE TITLE
API: compute_features should be more flexible

### ISSUE THREAD

**Issue by dengemann** [DavidSabbagh/meegpowreg#15]
What features are computed should be up to the user. If someone only wants covariances, it is silly to compute all the other features too.

**Comment by dengemann** [comment]
We could have a parameter like ```compute_features(epochs, features=('psds', 'freqs', 'covs'))```

And then inside the function loop over the features lists to compute only those asked for.
Checking can be done to throw errors if an unknown feature type is asked for.
The return value would always be a dictionary but its size would depend on the length of `features`.

Finally `compute_features(epochs, features='covs')` should also work.

**Comment by DavidSabbagh** [comment]
very good idea
