### ISSUE TITLE
FIX: install is requiring sklearn 0.23

### ISSUE THREAD

**Issue by dengemann** [DavidSabbagh/meegpowreg#4]
Doing a python setup.py develop makes me install an older scikit learn version, which is not nice.
Is this really necessary or can we change it to `scikit-learn>=0.23.2` ? cc @DavidSabbagh

**Comment by agramfort** [comment]
It’s due pyriemann

**Comment by agramfort** [comment]
Pyriemann is not really maintained anymore. I used pyvista master and scikit learn master and it works

**Comment by dengemann** [comment]
Shall we just change the requirements @agramfort ?

**Comment by dengemann** [comment]
Another option to consider is add PyRiemann via externals folder and maintain our own soup of it.

**Comment by agramfort** [comment]
I would remove pyriemann from setup.py until a new release in on pypi
and tell here to use pyriemann master

>

**Comment by dengemann** [comment]
Ok. Will look into that.
